version: 2
jobs:
  build:
    working_directory: ~/react-mobiledoc-editor
    docker:
      - image: circleci/node:12.16-browsers
    steps:
      - checkout
      - run: yarn install --pure-lockfile
      - run: yarn test
